"use client";
import {useState} from "react";
import data from "@/lib/travel-map-data.json";
type Visit={name:string;intensity:number;years:string;note:string};
const colors=["#e2e5de","#d1ddc5","#a1bc94","#608363","#234b3a"];
const level=(v:number)=>v<=0?0:v<.42?1:v<.72?2:v<.92?3:4;
const labels=["Not logged","Visited","Repeat visits","Frequent","Home / favorite"];
export function TravelMap(){
 const [selected,setSelected]=useState<Visit>(data.world.find(p=>p.name==="Canada")!.visit!);
 const [zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});
 const places=[...data.world.flatMap(p=>p.visit?[{key:`world-${p.name}`,visit:p.visit}]:[]),...data.points.map(p=>({key:p.pointKey,visit:p})),...data.us.flatMap(p=>p.visit?[{key:`us-${p.name}`,visit:p.visit}]:[])];
 function choose(name:string,visit:Visit|null){setSelected(visit||{name,intensity:0,years:"Not yet logged",note:"No travel notes recorded here yet."});}
 function region(p:typeof data.world[number],prefix:string){return <path key={p.name} d={p.path} fill={colors[level(p.visit?.intensity||0)]} className={selected.name===p.visit?.name?"map-region selected":"map-region"} role="button" tabIndex={p.visit?0:-1} aria-label={`${p.visit?.name||p.name}: ${labels[level(p.visit?.intensity||0)]}`} onClick={()=>choose(p.name,p.visit)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();choose(p.name,p.visit);}}}><title>{p.visit?.name||p.name}</title></path>;}
 return <section className="travel-explorer" aria-label="Interactive travel maps"><h2>Places that keep calling me back</h2><p>Select a country, state, or island marker to see visit years and notes. Darker green marks more frequent returns; gray means not yet logged.</p><div className="travel-map-layout"><div><div className="map-controls" aria-label="World map controls"><button onClick={()=>setZoom(z=>Math.min(4,z+.5))} disabled={zoom>=4}>Zoom in +</button><button onClick={()=>setZoom(z=>Math.max(1,z-.5))} disabled={zoom<=1}>Zoom out −</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0});}}>Reset</button>{zoom>1&&<><button aria-label="Pan west" onClick={()=>setPan(p=>({...p,x:Math.min(400,p.x+80)}))}>←</button><button aria-label="Pan east" onClick={()=>setPan(p=>({...p,x:Math.max(-400,p.x-80)}))}>→</button><button aria-label="Pan north" onClick={()=>setPan(p=>({...p,y:Math.min(200,p.y+60)}))}>↑</button><button aria-label="Pan south" onClick={()=>setPan(p=>({...p,y:Math.max(-200,p.y-60)}))}>↓</button></>}</div><svg className="travel-svg" viewBox="0 0 1000 520" aria-label="World travel map"><g transform={`translate(${500+pan.x} ${260+pan.y}) scale(${zoom}) translate(-500 -260)`}>{data.world.map(p=>region(p,"world"))}{data.points.map(p=><circle key={p.pointKey} cx={p.point![0]} cy={p.point![1]} r={p.radius/Math.sqrt(zoom)} fill={colors[level(p.intensity)]} stroke="#ae752e" strokeWidth={2} role="button" tabIndex={0} aria-label={`Select ${p.name}`} onClick={()=>setSelected(p)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(p);}}}><title>{p.name}</title></circle>)}</g></svg><h3>Across the United States</h3><svg className="travel-svg" viewBox="0 0 700 380" aria-label="United States travel map">{data.us.map(p=>region(p,"us"))}</svg></div><aside className="travel-inspector"><label>Choose a place<select value={places.find(p=>p.visit.name===selected.name)?.key||""} onChange={e=>{const place=places.find(p=>p.key===e.target.value);if(place)setSelected(place.visit);}}><option value="" disabled>Select a country or state</option><optgroup label="Countries and territories">{places.filter(p=>!p.key.startsWith("us-")).map(p=><option key={p.key} value={p.key}>{p.visit.name}</option>)}</optgroup><optgroup label="U.S. states">{places.filter(p=>p.key.startsWith("us-")).map(p=><option key={p.key} value={p.key}>{p.visit.name}</option>)}</optgroup></select></label><div aria-live="polite"><h3>{selected.name}</h3><p className="eyebrow">{labels[level(selected.intensity)]}</p><h4>Visit years</h4><p>{selected.years}</p><p>{selected.note}</p></div></aside></div><ul className="map-legend">{labels.map((label,i)=><li key={label}><span style={{background:colors[i]}}/>{label}</li>)}</ul><p className="small-note">Travel history imported from my earlier site. Shading represents return frequency, not an exact trip count. Map geography: Natural Earth and U.S. Census Bureau, via World Atlas and US Atlas.</p></section>;
}
